apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin-board-deployment
  labels:
    app: bulletin-board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bulletin-board
  template:
    metadata:
      labels:
        app: bulletin-board
    spec:
      containers:
      - name: bulletin-board
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
